# Generated by Django 4.2.3 on 2023-08-08 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_upload_post_file_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ManyToManyField(related_name='posts_media', to='posts.media'),
        ),
        migrations.AlterField(
            model_name='media',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_item', to='posts.post'),
        ),
    ]
