# Generated by Django 4.2.3 on 2023-08-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_media_alter_media_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
    ]
