# Generated by Django 4.2.3 on 2023-08-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_post_poster_remove_post_file_video_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.ManyToManyField(blank=True, null=True, related_name='associated_posts', to='posts.image'),
        ),
    ]
