# Generated by Django 4.2.3 on 2023-08-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_audio_audio_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.ManyToManyField(blank=True, related_name='associated_posts', to='posts.image'),
        ),
    ]
