# Generated by Django 4.2.3 on 2023-08-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audios',
            field=models.ManyToManyField(blank=True, related_name='associated_posts', to='posts.audio'),
        ),
        migrations.AlterField(
            model_name='post',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='associated_posts', to='posts.video'),
        ),
    ]
