# Generated by Django 4.2.3 on 2023-08-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_post_audios_alter_post_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='static/img/defult.jpg', null=True, upload_to='blog/'),
        ),
    ]
