# Generated by Django 4.2.3 on 2023-08-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_date_of_birth_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='static/img/defult.jpg', null=True, upload_to='blog/'),
        ),
    ]
